import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
   return (
      <>
         <Head>
            <title>Ecommerce Product Page</title>
            <meta name="description" content="Generated by Frontend Mentor" />
            <link rel="icon" href="/images/favicon-32x32.png" />
         </Head>

         <main className={styles.main}>
            <h1>product page</h1>
         </main>
      </>
   )
}

export default Home
